# classification

In [17]:
import pandas as pd

In [18]:
# sample classification data

In [19]:
data = {
    "hours_studied":[1,2,3,4,5,6,7,8,9,10],
    "passed":[0,0,0,0,0,1,1,1,1,1]
}

In [20]:
data

{'hours_studied': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 'passed': [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]}

In [21]:
df = pd.DataFrame(data)

In [22]:
df

   hours_studied  passed
0              1       0
1              2       0
2              3       0
3              4       0
4              5       0
5              6       1
6              7       1
7              8       1
8              9       1
9             10       1

In [23]:
# separate input and output

In [24]:
x = df[["hours_studied"]]
y = df[["passed"]]

In [25]:
print(x)

   hours_studied
0              1
1              2
2              3
3              4
4              5
5              6
6              7
7              8
8              9
9             10

In [26]:
print(y)

   passed
0       0
1       0
2       0
3       0
4       0
5       1
6       1
7       1
8       1
9       1

In [27]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\yr714\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in c:\users\yr714\anaconda3\lib\site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.8.0 in c:\users\yr714\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\yr714\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\yr714\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

In [28]:
import sklearn
print(sklearn.__version__)

1.7.2

In [29]:
# split data into training and testing

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [32]:
print(X_train)

   hours_studied
5              6
0              1
7              8
2              3
9             10
4              5
3              4
6              7

In [33]:
print(X_test)

   hours_studied
8              9
1              2

In [34]:
print(y_train)

   passed
5       1
0       0
7       1
2       0
9       1
4       0
3       0
6       1

In [35]:
print(y_test)

   passed
8       1
1       0

In [36]:
# import logistic regression

In [37]:
from sklearn.linear_model import LogisticRegression

In [38]:
# create and train model

In [39]:
model = LogisticRegression()

In [42]:
model.fit(X_train,y_train)

C:\Users\yr714\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [43]:
#prediction

In [44]:
y_pred = model.predict(X_test)

In [45]:
y_pred

array([1, 0])

In [46]:
X_test

   hours_studied
8              9
1              2

In [47]:
y_test

   passed
8       1
1       0

In [48]:
new_hours = pd.DataFrame({"hours_studied": [7.5]})

In [49]:
new_hours

   hours_studied
0            7.5

In [54]:
from sklearn.metrics import accuracy_score

In [51]:
predicted_marks

array([1])

In [50]:
predicted_marks = model.predict(new_hours)

In [55]:
accuracy_score(y_test,y_pred)

1.0

In [57]:
y_test

   passed
8       1
1       0

In [58]:
y_prob = model.predict_proba(X_test)

In [60]:
y_prob

array([[0.01799637, 0.98200363],
       [0.98200563, 0.01799437]])